version: "3.8"
name: simple-ecommerce-service

services:
  postgres-db:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  ecommerce:
    build: .
    volumes:
      - ./ecommerce:/code
    env_file:
      - ./.env
    depends_on:
      - postgres-db

volumes:
  postgres-db:
